#!/usr/bin/env python3

"""
    author:     Rafael Schreiber
    version:    v0.0.2
    date:       04-12-2018
    desc:       port 24 no access mode
"""

import os
import sys


HOME = os.getenv("HOME")
PWD = os.getenv("PWD")
SERVER = "github.com"


def isGit():
    if os.system("which git > /dev/null 2>&1") != 0:
        print("Sorry, git isn't installed please install git and restart the program")
        exit(1)
    else:
        return True


def isConnection():
    if os.system("ping -c 1 " + SERVER + " > /dev/null 2>&1") == 0:
        return True
    else:
        print("Sorry, there is no connection to " + SERVER)
        exit(1)


def isValidUser(username):
    if username is None:
        return False
    if os.system("curl -s --head https://" + SERVER + "/" + username +
                 " | head -n 1 | grep \"HTTP/1.[01] [23]..\" > /dev/null") == 0:
        return True
    else:
        return False


def isValidPath(path):
    try:
        os.chdir(path)
        os.chdir(PWD)
        return True
    except FileNotFoundError:
        return False


def isValidRepo(username, repo):
    if repo is None:
        return False
    if os.system("curl -s --head https://" + SERVER + "/" + username + '/' + repo +
                 " | head -n 1 | grep \"HTTP/1.[01] [23]..\" > /dev/null") == 0:
        return True
    else:
        print("It seems, that your repo is private. Do you want to change it? (y/n)")
        while True:
            ans = str(input(">>> "))
            if ans.lower() == "y":
                getRepo(username)
            elif ans.lower() == "n":
                return True
            else:
                print("Invalid input!\n")


def pathCleaner(path):
    if path[0] == '~':
        return HOME + path[1:]
    elif path[0] == '/':
        return path
    else:
        return PWD + '/' + path


def download(user, repo, location):
    try:
        os.makedirs(location)
    except PermissionError:
        print("Sorry, you don't have the permissions to save the files in this location")
        exit(1)
    except FileExistsError:
        pass
    os.chdir(location)
    os.system("git clone https://" + SERVER + "/" + user + "/" + repo)


def getUsername(msg):
    print(msg)
    while True:
        username = str(input(">>> "))
        if isValidUser(username):
            return username
        else:
            print("Sorry this user doesn't exist\n")


def getRepo(username):
    print("Which repository from " + username + " do you want to download?")
    while True:
        repo = str(input(">>> "))
        if isValidRepo(username, repo):
            return repo
        else:
            print("Sorry this repository doesn't exist\n")


def clone():
    # get username
    if isValidUser(sys.argv[2]):
        username = sys.argv[2]
    else:
        username = getUsername("From which user, do you want to fetch some repositories?")

    # get repo
    if isValidRepo(username, sys.argv[3]):
        repo = sys.argv[3]
    else:
        repo = getRepo(username)

    # get saving location
    if sys.argv[4] is None:
        location = "./"
    else:
        location = pathCleaner(sys.argv[4])

    # download repo
    download(username, repo, location)


def pull():
    if sys.argv[2] is None:
        location = "./"
    else:
        location = pathCleaner(sys.argv[2])
    os.chdir(location)
    os.system("git pull")


def push():
    if sys.argv[2] is None:
        print("Enter a commit message:")
        commit_message = str(input(">>> "))
        os.system("git add -A")
        os.system("git commit -m \"" + commit_message + "\"")
        os.system("git push")

    else:
        commit_message = sys.argv[2]
        os.system("git add -A")
        os.system("git commit -m \"" + commit_message + "\"")
        os.system("git push")


def init():
    if isValidUser(sys.argv[2]):
        username = sys.argv[2]
    else:
        username = getUsername("On which user do you want to initialize a repository?")

    if sys.argv[3] is None:
        print("Enter a project name:")
        while True:
            projname = str(input(">>> "))
            if len(projname) == 0:
                print("Invalid input!\n")
                continue
            isContinue = False
            for char in projname:
                if char == ' ':
                    print("Project name can not contain spaces!\n")
                    isContinue = True
                    break
            if isContinue:
                continue
            else:
                break
    else:
        projname = sys.argv[3]

    if len(os.listdir(PWD)) != 0:
        os.mkdir(projname)
        os.chdir(projname)

    os.system("echo \"# " + projname + "\" >> README.md")
    os.system("git init")
    os.system("git add -A")
    os.system("git commit -m \"Initial Commit\"")
    os.system("git remote add origin https://" + SERVER + "/" + username + "/" + projname + ".git")
    os.system("git push -u origin master")


def helpme():
    print("ggit, version 0.0.1")
    print("(Licensed under the GNU General Public License v3.0)\n")

    print("usage: ggit [-h] [username] [repository] [location]\n")

    print("-h : Displays this page\n")

    print("username   : Server username, where the repository is located")
    print("repository : name of the repository")
    print("location   : where the download should be saved (default is pwd)\n")

    print("NOTE: The program asks if you have given wrong command line arguments\n")

    print("Please send bugs and crashes to raf.schreiber@gmail.com Thanks :)")


def main():
    # corrects all command line arguments
    for i in [1, 2, 3, 4]:
        try:
            sys.argv[i] = sys.argv[i]
        except IndexError:
            sys.argv.append(None)

    # get help
    if sys.argv[1] is None:
        helpme()
        exit(1)

    if sys.argv[1] == "-h" or sys.argv[1] == "--help":
        helpme()
        exit(0)

    isGit()  # crashes when git isn't installed
    isConnection()  # crashes when there is no connection to the GitHub servers

    if sys.argv[1] == "clone":
        clone()
        exit(0)
    elif sys.argv[1] == "pull":
        pull()
        exit(0)
    elif sys.argv[1] == "push":
        push()
        exit(0)
    elif sys.argv[1] == "init":
        init()
        exit(0)
    else:
        helpme()
        exit(1)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit(1)
    except EOFError:
        exit(1)
